### ISSUE TITLE
NLog 5.0.0-beta10 no longer available.

### ISSUE THREAD

**Issue by master117** [ImoutoChan/ImoutoBooruParser#1]
https://www.nuget.org/packages/NLog/5.0.0-beta10

NLog 5.0.0-beta10 has been unlisted, which leads to failure to install ImoutoBooruParser through NuGet:

`PM> Install-Package Imouto.BooruParser`

`Attempting to gather dependency information for package 'Imouto.BooruParser.1.0.0' with respect to project 'Project', targeting '.NETFramework,Version=v4.6.1'`

`Attempting to resolve dependencies for package 'Imouto.BooruParser.1.0.0' with DependencyBehavior 'Lowest'`

`Install-Package : Unable to find a version of 'NLog' that is compatible with 'Imouto.BooruParser 1.0.0 constraint: NLog (>= 5.0.0-beta10)'.`

**Comment by ImoutoChan** [comment]
Thanks, fixed version is available on nuget.
