### ISSUE TITLE
Updated Wiki?

### ISSUE THREAD

**Issue by Atulin** [ImoutoChan/ImoutoBooruParser#2]
So far there is zero instructions on how to use this parser whatsoever. The only things I know is how to initialize a new ``DanbooruLoader``, and that it uses a metric shitton of dependencies.

Any chance of populating the wiki with _Getting Started_, _Fetching Pictures_, _Authenticating_, et cetera?

**Comment by ImoutoChan** [comment]
Hi

Well, there is a small sample in the Readme. 
Yandere is working just fine without any authentication. Sankaku and Danbooru have login and passhash/apiKey as params in constructor. No need to do anything else to authenticate.

All of loaders implement 

```
public interface IBooruAsyncLoader
    {
        Task<Post> LoadPostAsync(int postId);

        Task<SearchResult> LoadSearchResultAsync(string tagsString);

        Task<List<NoteUpdateEntry>> LoadNotesHistoryAsync(DateTime lastUpdateTime);

        Task<List<PostUpdateEntry>> LoadTagHistoryUpToAsync(DateTime toDate);

        Task<List<PostUpdateEntry>> LoadTagHistoryFromAsync(int fromId);

        Task<List<PostUpdateEntry>> LoadFirstTagHistoryPageAsync();
    }
```

this interface, so you can call its members to access data. Pictures can't be fetched directly with this library, but you can download them from links that you'll get in post metadata after calling LoadPostAsync().

Also, I can see only 3 dependency.
```
  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.6.15" />
    <PackageReference Include="Newtonsoft.Json" Version="10.0.3" />
    <PackageReference Include="NLog" Version="4.5.0-rc04" />
  </ItemGroup>
```

You probably use it from .net framework app? When you access .net standard library from .net framework app, it downloads a lot of assemblies for compatibility.

**Comment by Atulin** [comment]
Still, could use some more documentation IMO. Even something smple, as fetching a title of the first post on Sankaku/Gelbooru/Yandere/whatever.

Also, yes, I am usin .net. That explains the dependencies.
