### ISSUE TITLE
Cannot retrieve the orginal image

### ISSUE THREAD

**Issue by Sesshoumaru-sama** [ImoutoChan/ImoutoBooruParser#3]
I'm trying to use the SankakuLoader within one of my experiments with discord.
The search returns proper results and I can get to the Orginal URL, but there the issue starts.

When I put this URL to a brower, I get redirected to a page that says that the URL is expired.
For posting the image on dicord I would need a stable URL or possibilty to download the image (to bytes to post as memory stream).

Can you help me here? Do I make an error?

**Comment by ImoutoChan** [comment]
It looks like sankaku has added a protection to their images. I'll see what I can do about it.

**Comment by ImoutoChan** [comment]
I've uploaded a package with the fix. You can try using it.

**Comment by Sesshoumaru-sama** [comment]
I will try and give you feedback asap :+1: 
Edit: Works now, image can be retrieved - perfect.
